name: test

on:
  push:
  pull_request:
  schedule:
    - cron: '25 10 * * *'
  workflow_dispatch:

jobs:
  ruby-versions:
    if: ${{ startsWith(github.repository, 'ruby/') || github.event_name != 'schedule' }}
    uses: ruby/actions/.github/workflows/ruby_versions.yml@master
    with:
      engine: cruby

  test:
    needs: ruby-versions
    strategy:
      fail-fast: false
      matrix:
        ruby: ['head']
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        include:
          - { ruby: mswin, os: windows-latest }
    runs-on: ${{ matrix.os || 'ubuntu-latest' }}
    steps:
    - name: git config
      run: |
        git config --global core.autocrlf false
        git config --global core.eol lf
        git config --global advice.detachedHead 0
    - uses: actions/checkout@v4
    - name: Set up Ruby ${{ matrix.ruby }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        rubygems: latest
    - name: Experiment with a manual bundle install
      run: bundle install
    - name: Run test
      run: rake # Attempting without 'bundle exec'
      continue-on-error: ${{matrix.ruby == 'truffleruby-head'}}
    - id: build
      run: |
        rake build
        ruby ext/io/console/extconf.rb
        cat Makefile
      env:
        RUNNING_OS: ${{matrix.os}}
        PLATFORM: ${{ startsWith(matrix.ruby, 'jruby') && 'java' || '' }}
      shell: bash
